# Generated by Django 5.0 on 2023-12-21 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_alter_surveyresponse_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients_groups',
            field=models.ManyToManyField(related_name='notifications_received', to='socialnetwork.group'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients_users',
            field=models.ManyToManyField(related_name='notifications_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
