# Generated by Django 4.2.7 on 2023-12-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_studentprofile_lecturerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='media',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(null=True, upload_to='users/covers'),
        ),
        migrations.DeleteModel(
            name='LecturerProfile',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
