# Generated by Django 5.0 on 2023-12-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_notification_post_question_reaction_survey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='media',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/avatars/%Y/%m'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_images',
            field=models.ImageField(null=True, upload_to='users/cover_images/%Y/%m'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
